{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-auc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/AUC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/AUC/AUC_{{ version }}.tar.gz
  sha256: 836b25b654a82f6ab69b86be95acc22a214da0ad06d71eab787ae1ebe721ae1f

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('AUC')"           # [not win]
    - "\"%R%\" -e \"library('AUC')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=AUC
  license: GPL-2.0-or-later
  summary: 'This package includes functions to compute the area under the curve of selected measures: The area under the sensitivity curve (AUSEC), the area under the specificity curve (AUSPC), the area under the accuracy curve (AUACC), and the area under the receiver operating characteristic curve (AUROC). The curves can
    also be visualized. Support for partial areas is provided.'
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: AUC
# Type: Package
# Title: Threshold independent performance measures for probabilistic classifiers.
# Version: 0.3.0
# Date: 2013-09-30
# Author: Michel Ballings and Dirk Van den Poel
# Maintainer: Michel Ballings <Michel.Ballings@UGent.be>
# Description: This package includes functions to compute the area under the curve of selected measures: The area under the sensitivity curve (AUSEC), the area under the specificity curve (AUSPC), the area under the accuracy curve (AUACC), and the area under the receiver operating characteristic curve (AUROC). The curves can also be visualized. Support for partial areas is provided.
# License: GPL (>= 2)
# ByteCompile: true
# Packaged: 2013-09-30 14:45:12 UTC; mballing
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-09-30 17:41:33
