appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: fwkXKGBdCbMg78ZLUkg6BBbmCKYNw0+n0V45TTffd7w5U0uwtFkSrZaIj5ZxGjxC0ZhZj2nsHEpGy7nTo+O8bOHCFggT8Nbut6VuU0rBlrKeqLpSKf+hroNrbwx0lnBaSEqhbUKV2QvaIlC8um9EtzKpLJBpuQgogVoVz2dYn4Ik9lNXPERYJQtsXDzuabx6XwYfuD70JfWZT1FihSO2zh+5qm0mi7nRt9cAIf7id7x4oPf+HrTb5vFpXrHyUU9kOuH/f9bHttrMaiZ+7DS+RxKRLS260YJsq9J2VhnM9GV+3bCdgCYh5yQ2MNpMJyhw5AKNMndJ1YEWz2BUn7NB0gau5Fwsb/9rlrynomPDBBAhnkDvLbmAj07Hpg5KG4hgtao+K4KX499Nm9zVX8QNy+q5QQc30Oz6NLYJfPdA/ET1bExCGnyVbzYn1cSmuXO1yY1+aLX9GewpLVQbZ+oyX0dUqJsz27E/hS+R8Bd3IKddMmYd8bU81ln9/FQHJrNPC1+Afh0+VHxtU2IebTvuGlNYW8qKyb0InlUeM5BTykuTU+kLB6xNqsBaFXJ4pR9gIE/O/r0+EkyaL8h/Bk0qA2h3OLhkua326eaEcTxGHxN2wDb25M08G6RrQkq0yCb6smDb0H5hOZTk1jBq8yySBCV20lOnT9XtgG0Gl5yTQwM=
